### PR TITLE
Add DICOM information as drop down on image

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by floryst** [comment]
Looks good! Can we have a fully opaque background for the popup? My concern is readability of the white text.

**Comment by cjh1** [comment]
Sure, was just following the mock-up.

**Comment by floryst** [comment]
The mockup is definitely a good starting point. I just noticed that really bright window/level settings makes the info text unreadable.

**Comment by floryst** [comment]
Once this is ready, I'll merge my paint tool PR after merging this, since there will be some conflicts with VtkTwoView.

**Comment by cjh1** [comment]
@floryst Done

**Comment by floryst** [comment]
LGTM, thanks!

**Pull request merged**
