### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by floryst**
- Updates packages, and migrates to webpack v5 (and upgrades vue/cli)
- removes disused code, and moves componentX to components

### CODE REVIEW

**Comment by floryst** [comment]
FYI @cjh1 this represents a fairly major upgrade to our dependencies, and removes a bunch of dead code that I've been meaning to remove.

**Review by cjh1 — APPROVED** [review]
@floryst Tested these changes out, LGTM. Nice to see the end of componentsX!

**Comment by floryst** [comment]
Sourcemap config might have changed when upgrading vue-cli. I'll look into it.

**Comment by cjh1** [comment]
I removed my `node_modules` and reinstall and everything looks good now :smile: Sorry for the noise ...

**Pull request merged**
