### PR TITLE
feat: Move dataset spefic view config into own store

### PR DESCRIPTION
**Pull request by cjh1**
This moves slice and window related configuration into a separate store. This allows us to save these values on a per dataset basis.

Note: That we will need to move the zoom level into the store too, that will be done in a follow up.

### CODE REVIEW

**Comment by floryst** [comment]
The ruler doesn't work. When clicking to place, I get the following error:

Screen Shot 2022-06-07 at 9 54 15 AM

**Comment by cjh1** [comment]
Ok, will take a look

**Comment by cjh1** [comment]
@floryst The error should now be resolved.

**Comment by floryst** [comment]
LGTM!

**Pull request merged**
